In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv("C:/Users/hp/Downloads/BitcoinPrice/Bitcoin_price.csv")

In [7]:
df.head()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [10]:
df.tail()

Date         Price
360  2019-08-20 00:00:00  10746.507692
361  2019-08-21 00:00:00  10169.094167
362  2019-08-22 00:00:00  10030.746667
363  2019-08-23 00:00:00  10255.977500
364  2019-08-24 00:00:00  10158.540833

# DATA PREPROCESSING


In [11]:
df.shape

(365, 2)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
Date     365 non-null object
Price    365 non-null float64
dtypes: float64(1), object(1)
memory usage: 4.3+ KB


In [14]:
df.drop(['Date'],1,inplace=True)

In [15]:
df.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [16]:
#prediction for next 30 days
p_days=30
df['Prediction']=df[['Price']].shift(-p_days)

In [17]:
df.head()

Price   Prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [18]:
df.tail()

Price  Prediction
360  10746.507692         NaN
361  10169.094167         NaN
362  10030.746667         NaN
363  10255.977500         NaN
364  10158.540833         NaN

In [19]:
X=np.array(df.drop(['Prediction'],1))
X=X[: len(df) -p_days]

In [20]:
X.shape

(335, 1)

In [21]:
X

array([[ 6719.42923077],
       [ 6673.27416667],
       [ 6719.26615385],
       [ 7000.04      ],
       [ 7054.27642857],
       [ 6932.6625    ],
       [ 6981.94615385],
       [ 7100.94666667],
       [ 7247.93538462],
       [ 7260.94923077],
       [ 7326.8525    ],
       [ 7113.06923077],
       [ 6433.27166667],
       [ 6444.80416667],
       [ 6366.1075    ],
       [ 6286.42583333],
       [ 6297.87769231],
       [ 6296.32083333],
       [ 6273.1375    ],
       [ 6450.17923077],
       [ 6499.0625    ],
       [ 6518.655     ],
       [ 6480.64416667],
       [ 6400.60083333],
       [ 6296.63166667],
       [ 6335.82666667],
       [ 6418.56266667],
       [ 6669.99083333],
       [ 6709.3125    ],
       [ 6710.445     ],
       [ 6639.30416667],
       [ 6412.45916667],
       [ 6468.63166667],
       [ 6535.47666667],
       [ 6677.3425    ],
       [ 6550.47416667],
       [ 6593.135     ],
       [ 6590.96833333],
       [ 6562.64166667],
       [ 6470.4025    ],


In [22]:
Y=np.array(df['Prediction'])
Y=Y[: -p_days]

In [23]:
Y.shape

(335,)

In [24]:
Y

array([ 6639.30416667,  6412.45916667,  6468.63166667,  6535.47666667,
        6677.3425    ,  6550.47416667,  6593.135     ,  6590.96833333,
        6562.64166667,  6470.4025    ,  6563.62833333,  6568.54916667,
        6581.48666667,  6558.5375    ,  6618.56769231,  6621.71166667,
        6563.00916667,  6248.63583333,  6260.53083333,  6260.64583333,
        6299.39916667,  6452.57166667,  6596.61833333,  6596.27615385,
        6568.04076923,  6487.44416667,  6488.82583333,  6531.60166667,
        6498.48583333,  6481.426     ,  6508.31      ,  6478.0825    ,
        6473.75333333,  6465.9175    ,  6448.22166667,  6382.66833333,
        6309.45285714,  6310.28416667,  6342.28083333,  6387.67416667,
        6363.79583333,  6391.87333333,  6436.965     ,  6445.35416667,
        6538.79      ,  6486.25166667,  6411.28083333,  6399.03333333,
        6378.26833333,  6401.93666667,  6372.06333333,  6176.155     ,
        5615.18      ,  5596.1925    ,  5558.24333333,  5606.04416667,
      

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,Y,test_size=0.2)

In [27]:
P_days_array=np.array(df.drop(['Prediction'],1))[p_days:]

In [28]:
print(P_days_array)

[[ 6639.30416667]
 [ 6412.45916667]
 [ 6468.63166667]
 [ 6535.47666667]
 [ 6677.3425    ]
 [ 6550.47416667]
 [ 6593.135     ]
 [ 6590.96833333]
 [ 6562.64166667]
 [ 6470.4025    ]
 [ 6563.62833333]
 [ 6568.54916667]
 [ 6581.48666667]
 [ 6558.5375    ]
 [ 6618.56769231]
 [ 6621.71166667]
 [ 6563.00916667]
 [ 6248.63583333]
 [ 6260.53083333]
 [ 6260.64583333]
 [ 6299.39916667]
 [ 6452.57166667]
 [ 6596.61833333]
 [ 6596.27615385]
 [ 6568.04076923]
 [ 6487.44416667]
 [ 6488.82583333]
 [ 6531.60166667]
 [ 6498.48583333]
 [ 6481.426     ]
 [ 6508.31      ]
 [ 6478.0825    ]
 [ 6473.75333333]
 [ 6465.9175    ]
 [ 6448.22166667]
 [ 6382.66833333]
 [ 6309.45285714]
 [ 6310.28416667]
 [ 6342.28083333]
 [ 6387.67416667]
 [ 6363.79583333]
 [ 6391.87333333]
 [ 6436.965     ]
 [ 6445.35416667]
 [ 6538.79      ]
 [ 6486.25166667]
 [ 6411.28083333]
 [ 6399.03333333]
 [ 6378.26833333]
 [ 6401.93666667]
 [ 6372.06333333]
 [ 6176.155     ]
 [ 5615.18      ]
 [ 5596.1925    ]
 [ 5558.24333333]
 [ 5606.04

In [29]:
from sklearn.ensemble import RandomForestRegressor


In [31]:
RF= RandomForestRegressor(n_estimators=1000,random_state=1)

In [34]:
RF.fit(X_train,y_train)
print('Random Forest Accuracy: {:.2f}%'.format(RF.score(X_test,y_test)*100))

Random Forest Accuracy: 83.16%


In [35]:
RF_predict=RF.predict(X_test)
print(RF_predict)

[ 5270.7569675  11402.91323917 10349.14113417 10055.24146833
  4094.7559675   5213.37586333  3635.86305955  3902.70174833
 10431.66506167  9914.54784885  5209.13905083  5838.13201917
  6645.37944923  8114.702055    6160.219965    3921.20494905
  6797.37342083  6379.00398667  6269.37649833  6701.4450625
  4189.08983     3919.74521321  6486.42589833 10158.84395833
  4269.42290769  3856.73900583  4538.92225805  6360.19117667
  8047.33708583  3851.016205    5086.4998425   6564.55305417
  3948.61979583  7235.73423083  5758.29953333  6673.32164173
  5759.79723083  4525.79884096 10347.2550925   4102.89708167
  6363.3592625   4053.45036421  4023.36444205  6631.51808167
 11038.9644635   4189.08983     5882.14946917  3863.66889186
  4043.34787    10051.08503833  6490.615161    4538.92225805
  4538.92225805  5466.33842167  4234.93731583  3921.20494905
  4633.51548147  6507.9894775   3929.4939775   6349.35157583
 11233.3422875   5262.570765   10348.25732667  3928.53737667
 12276.18325     5929.010

In [36]:
print(y_test)

[ 5274.14583333 10021.325       9160.0675     10449.62666667
  3912.28583333  6452.57166667  4025.02583333  5421.52666667
 10255.9775     11577.69538462  5305.275       4293.84083333
  6056.4175      8646.195       6309.45285714  3630.39666667
  5654.35333333  5558.24333333  6436.965       6590.96833333
  5364.99166667  3610.74833333  6372.06333333 10158.54083333
  8663.6425      3829.56833333  3589.26083333  6568.04076923
  8342.77        5465.515       3832.92166667  9096.28583333
  3867.13833333  8546.17166667  6382.66833333  7265.96333333
  4309.3375      3822.62666667 10300.41166667  3458.06666667
  6342.28083333  4675.1125      3454.19461538  6535.47666667
  9725.4025      3982.85083333  5596.1925      3656.73583333
  3933.95416667 10292.38333333  6498.48583333  3567.76333333
  3868.4875      3435.34        5306.695       3933.14333333
  3470.07916667  6412.45916667  4026.63583333  6621.71166667
 11886.88615385  5109.94666667 10746.50769231  5197.75076923
 12567.70384615  5697.92

In [37]:
RF_predict_30=RF.predict(P_days_array)
print(RF_predict)

[ 5270.7569675  11402.91323917 10349.14113417 10055.24146833
  4094.7559675   5213.37586333  3635.86305955  3902.70174833
 10431.66506167  9914.54784885  5209.13905083  5838.13201917
  6645.37944923  8114.702055    6160.219965    3921.20494905
  6797.37342083  6379.00398667  6269.37649833  6701.4450625
  4189.08983     3919.74521321  6486.42589833 10158.84395833
  4269.42290769  3856.73900583  4538.92225805  6360.19117667
  8047.33708583  3851.016205    5086.4998425   6564.55305417
  3948.61979583  7235.73423083  5758.29953333  6673.32164173
  5759.79723083  4525.79884096 10347.2550925   4102.89708167
  6363.3592625   4053.45036421  4023.36444205  6631.51808167
 11038.9644635   4189.08983     5882.14946917  3863.66889186
  4043.34787    10051.08503833  6490.615161    4538.92225805
  4538.92225805  5466.33842167  4234.93731583  3921.20494905
  4633.51548147  6507.9894775   3929.4939775   6349.35157583
 11233.3422875   5262.570765   10348.25732667  3928.53737667
 12276.18325     5929.010

In [39]:
df.tail(30)

Price  Prediction
335   9774.257500         NaN
336   9725.402500         NaN
337   9500.324167         NaN
338   9533.979333         NaN
339   9539.712500         NaN
340   9873.811667         NaN
341  10088.800000         NaN
342  10478.901667         NaN
343  10790.630000         NaN
344  10826.275000         NaN
345  11713.161667         NaN
346  11759.019167         NaN
347  11703.738333         NaN
348  11803.888333         NaN
349  11816.912500         NaN
350  11586.172500         NaN
351  11377.804167         NaN
352  11397.801667         NaN
353  11144.389167         NaN
354  10450.813333         NaN
355   9988.947500         NaN
356  10230.733333         NaN
357  10292.383333         NaN
358  10295.117500         NaN
359  10605.825833         NaN
360  10746.507692         NaN
361  10169.094167         NaN
362  10030.746667         NaN
363  10255.977500         NaN
364  10158.540833         NaN